-- V1: Create merkle_metadata table (H2-compatible version for tests)
-- This table stores metadata about each merkle instance in the system

CREATE TABLE merkle_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier VARCHAR(64) NOT NULL UNIQUE,
    scheme VARCHAR(20) NOT NULL DEFAULT 'mpf',
    root_hash VARCHAR(128),
    record_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP,
    metadata JSON,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    version BIGINT DEFAULT 0
);

-- Create indexes for common queries
CREATE INDEX idx_merkle_status ON merkle_metadata(status);
CREATE INDEX idx_merkle_created_at ON merkle_metadata(created_at DESC);
CREATE INDEX idx_merkle_scheme ON merkle_metadata(scheme);

-- Add check constraint for valid statuses
ALTER TABLE merkle_metadata
ADD CONSTRAINT chk_merkle_status
CHECK (status IN ('ACTIVE', 'BUILDING', 'ARCHIVED', 'DELETED'));

-- Add check constraint for valid merkle schemes
ALTER TABLE merkle_metadata
ADD CONSTRAINT chk_merkle_scheme
CHECK (scheme IN ('mpf', 'jmt'));

-- Add check constraint for non-negative record count
ALTER TABLE merkle_metadata
ADD CONSTRAINT chk_record_count
CHECK (record_count >= 0);
